namespace MateMCP.Agent.Desktop;

public static class AgentUi
{
    public const string Html = """
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MateMCP Agent</title>
<style>:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color-scheme:light dark}body{max-width:980px;margin:32px auto;padding:0 20px}.muted{opacity:.65}.card{border:1px solid #8886;border-radius:12px;padding:16px;margin:12px 0}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}button,input{font:inherit;padding:8px 10px;border-radius:8px;border:1px solid #8888}button{cursor:pointer}.danger{color:#d33}.ok{color:#16803c}.approval{border-left:4px solid #d88b00}.approval-low{border-left-color:#16803c}.approval-medium,.approval-sensitive{border-left-color:#d88b00}.approval-high{border-left-color:#d33}.approval-critical{border-left-color:#8f121d;box-shadow:0 0 0 1px #8f121d55}.approval-unknown{border-left-color:#7a4c9c}.approval-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.risk{font-weight:700}.risk-high,.risk-critical{color:#d33}.risk-sensitive,.risk-medium{color:#d88b00}.risk-low{color:#16803c}.risk-unknown{color:#7a4c9c}.effect{margin:12px 0;padding:12px;border-radius:9px;background:#8881;font-size:1.02rem}.impact-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:10px 0}.impact-grid>div{border:1px solid #8884;border-radius:8px;padding:8px}.impact-grid span{display:block;font-size:.78rem;opacity:.65}.flags{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.flag{border:1px solid #d335;border-radius:999px;padding:4px 8px;font-size:.82rem}.impact-list{margin:7px 0 12px;padding-left:20px}.safer{padding:10px;border:1px solid #16803c55;background:#16803c12;border-radius:8px;margin:10px 0}.warning{padding:10px;border:1px solid #d335;background:#d331;border-radius:8px;margin:10px 0}.tech{margin:12px 0;border-top:1px solid #8884;padding-top:9px}.tech summary{cursor:pointer;font-weight:650}.tech pre{white-space:pre-wrap;word-break:break-word;background:#8881;border-radius:8px;padding:10px}.effect{margin-top:4px}label{display:flex;gap:6px;align-items:center}input[type=text],input[type=password]{min-width:240px;flex:1}.project{display:grid;grid-template-columns:1fr auto;gap:12px}.empty{padding:18px;text-align:center;opacity:.6}code{word-break:break-all}.msg{min-height:20px;margin:8px 0}@media(max-width:650px){.impact-grid{grid-template-columns:1fr}}</style></head>
<body><h1>MateMCP Agent</h1><div class="muted">Local management · only available from this computer</div><div id="message" class="msg"></div>
<section><h2>Pending approvals <span id="approvalCount"></span></h2><div id="approvalList"></div></section>
<section><h2>Always-allow rules</h2><div id="policyList"></div></section>
<section><h2>Credential usage audit</h2><div class="muted">Metadata only; secret values are never recorded.</div><div id="auditList"></div></section>
<section><h2>Secrets & credentials</h2><div class="muted">Values stay in the local OS credential store. AI clients can see names, descriptions, and authorized tools, but never secret values.</div><form id="secretForm" class="card"><div class="row"><input id="secretName" type="text" placeholder="Credential name (for example prod-ssh)" autocomplete="off" required><input id="secretValue" type="password" placeholder="Secret value" autocomplete="new-password" required></div><div class="row" style="margin-top:10px"><input id="secretDescription" type="text" placeholder="Description (optional)"><label><input id="secretShellTool" type="checkbox" checked>Allow shell_session_send_secret</label><button type="submit">Save credential</button></div></form><div id="secretList"></div></section>
<section><h2>Projects</h2><form id="projectForm" class="card"><input type="hidden" id="originalName"><div class="row"><input id="name" type="text" placeholder="Project name" required><input id="root" type="text" placeholder="Project folder path" required></div><div class="row" style="margin-top:10px"><label><input id="read" type="checkbox" checked>Read</label><label><input id="write" type="checkbox" checked>Write</label><label><input id="shell" type="checkbox" checked>Shell</label><button type="submit">Save project</button><button type="button" id="cancelEdit" hidden>Cancel edit</button></div></form><div id="projectList"></div></section>
<script>
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function message(text,bad=false){$('message').textContent=text;$('message').className='msg '+(bad?'danger':'ok');if(text)setTimeout(()=>{$('message').textContent=''},4000)}
async function json(url,options){const r=await fetch(url,options);if(!r.ok){let t=await r.text();try{t=JSON.parse(t).detail||t}catch{}throw new Error(t||r.statusText)}return r.status===204?null:r.json()}
function riskClass(a){const r=String(a.risk||'unknown').toLowerCase();return ['low','medium','sensitive','high','critical'].includes(r)?r:'unknown'}
function approvalFlags(a){const f=[];if(a.destructive)f.push('Destructive');if(a.requiresElevation)f.push('Elevated privileges');if(a.credentialExposure)f.push('Credential access');if(a.networkEffect)f.push('Network effect');if(a.persistenceEffect)f.push('Persistent change');return f}
function approvalHtml(a){const r=riskClass(a),flags=approvalFlags(a),reasons=(a.reasons||[]).slice(0,6),resources=(a.affectedResources||[]).slice(0,6),contributors=(a.contributors||[]).slice(0,8);const caution=(r==='critical'||r==='unknown')?`<div class="warning"><b>${r==='unknown'?'MateMCP cannot confidently classify this action.':'This action can have severe or difficult-to-reverse effects.'}</b><div>Review the effect, reasons, and technical details before approving.</div></div>`:'';const provenance=contributors.length?`<div><b>Analysis provenance</b><ul class="impact-list">${contributors.map(x=>`<li>${esc(x.source)} · ${esc(x.kind)} · ${x.authoritative?'authoritative':'non-authoritative'}</li>`).join('')}</ul></div>`:'';const broad=(a.canAllowSession||a.canAllowAlways)?`<div class="row" style="margin-top:8px">${a.canAllowSession?`<button onclick="decide('${a.id}','allow-session')">Approve for session</button>`:''}${a.canAllowAlways?`<button onclick="decide('${a.id}','allow-always')">Always allow</button>`:''}</div>`:`<div class="muted" style="margin-top:8px">Current risk policy requires a fresh decision for this risk level; broad trust is disabled.</div>`;return `<div class="card approval approval-${esc(r)}"><div class="approval-head"><b>${esc(a.capability)}</b><div class="risk risk-${esc(r)}">Risk: ${esc(a.risk||'Unknown')}${a.confidence?` · ${esc(a.confidence)} confidence`:''}</div></div>${caution}<div class="effect"><b>Expected effect:</b> ${esc(a.effect||'The exact effect is not known with high confidence.')}</div><div class="impact-grid"><div><span>Category</span><b>${esc(a.intentCategory||'Unknown')}</b></div><div><span>Reversibility</span><b>${esc(a.reversibility||'Unknown')}</b></div><div><span>Scope</span><b>${esc(a.target)}</b></div></div>${flags.length?`<div class="flags">${flags.map(x=>`<span class="flag">${esc(x)}</span>`).join('')}</div>`:''}${resources.length?`<div><b>Affected resources</b><ul class="impact-list">${resources.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${reasons.length?`<div><b>Why MateMCP rated it this way</b><ul class="impact-list">${reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${a.saferAlternative?`<div class="safer"><b>Safer alternative</b><div>${esc(a.saferAlternative)}</div></div>`:''}${a.preview?`<div><b>Preview</b><pre>${esc(a.preview)}</pre></div>`:''}<details class="tech"><summary>Technical details</summary><div><b>Target:</b> <code>${esc(a.target)}</code></div><pre>${esc(a.summary)}</pre>${provenance}</details><div class="muted">Expires ${new Date(a.expiresAt).toLocaleTimeString()}</div><div class="row" style="margin-top:10px"><button class="danger" onclick="decide('${a.id}','deny')">Deny</button><button onclick="decide('${a.id}','allow')">Approve once</button></div>${broad}</div>`}
async function loadApprovals(){try{const list=await json('/approvals');$('approvalCount').textContent=list.length?`(${list.length})`:'';$('approvalList').innerHTML=list.length?list.map(approvalHtml).join(''):'<div class="empty">No pending approvals</div>'}catch(e){message(e.message,true)}}
async function decide(id,decision){try{await json(`/approvals/${id}/${decision}`,{method:'POST'});await Promise.all([loadApprovals(),loadPolicies()])}catch(e){message(e.message,true)}}
async function loadPolicies(){try{const list=await json('/approval-policies');$('policyList').innerHTML=list.length?list.map(p=>`<div class="card project"><div><b>${esc(p.capability)}</b><div><code>${esc(p.target)}</code></div></div><button class="danger" onclick="removePolicy('${encodeURIComponent(p.capability)}','${encodeURIComponent(p.target)}')">Remove</button></div>`).join(''):'<div class="empty">No persistent approval rules</div>'}catch(e){message(e.message,true)}}
async function removePolicy(c,t){try{await json(`/approval-policies?capability=${c}&target=${t}`,{method:'DELETE'});message('Approval rule removed');await loadPolicies()}catch(e){message(e.message,true)}}
async function loadAudit(){try{const list=await json('/credential-audit?limit=100');$('auditList').innerHTML=list.length?list.map(a=>`<div class="card"><b>${esc(a.credential||'legacy entry')}</b> · <code>${esc(a.tool||a.capability)}</code><div>${esc(a.result)} · ${esc(a.target)}</div><div class="muted">${new Date(a.timestamp).toLocaleString()}</div></div>`).join(''):'<div class="empty">No credential usage recorded</div>'}catch(e){message(e.message,true)}}
async function loadSecrets(){try{const list=await json('/secrets');$('secretList').innerHTML=list.length?list.map(s=>`<div class="card project"><div><b>${esc(s.name)}</b><div class="muted">${esc(s.description||'No description')}</div><div class="muted">Allowed tools: ${esc((s.allowedTools||['shell_session_send_secret']).join(', ')||'none')}</div></div><button class="danger" onclick="removeSecret('${encodeURIComponent(s.name)}')">Remove</button></div>`).join(''):'<div class="empty">No credentials configured</div>'}catch(e){$('secretList').innerHTML=`<div class="empty danger">${esc(e.message)}</div>`}}
$('secretForm').onsubmit=async e=>{e.preventDefault();const payload={name:$('secretName').value,value:$('secretValue').value,description:$('secretDescription').value,allowedTools:$('secretShellTool').checked?['shell_session_send_secret']:[]};try{await json('/secrets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('secretForm').reset();$('secretShellTool').checked=true;message('Credential saved');await loadSecrets()}catch(e){message(e.message,true)}};
async function removeSecret(encoded){const name=decodeURIComponent(encoded);if(!confirm(`Remove credential "${name}"?`))return;try{await json(`/secrets/${encodeURIComponent(name)}`,{method:'DELETE'});message('Credential removed');await loadSecrets()}catch(e){message(e.message,true)}}
let projects=[];async function loadProjects(){try{projects=await json('/projects');$('projectList').innerHTML=projects.length?projects.map(p=>`<div class="card project"><div><b>${esc(p.name)}</b><div><code>${esc(p.root)}</code></div><div class="muted">${p.read?'Read ':''}${p.write?'Write ':''}${p.shell?'Shell':''}</div></div><div class="row"><button onclick="editProject('${encodeURIComponent(p.name)}')">Edit</button><button class="danger" onclick="removeProject('${encodeURIComponent(p.name)}')">Remove</button></div></div>`).join(''):'<div class="empty">No projects configured</div>'}catch(e){message(e.message,true)}}
function editProject(encoded){const name=decodeURIComponent(encoded),p=projects.find(x=>x.name===name);if(!p)return;$('originalName').value=p.name;$('name').value=p.name;$('root').value=p.root;$('read').checked=p.read;$('write').checked=p.write;$('shell').checked=p.shell;$('cancelEdit').hidden=false;$('projectForm').scrollIntoView({behavior:'smooth'})}
function resetForm(){$('projectForm').reset();$('read').checked=$('write').checked=$('shell').checked=true;$('originalName').value='';$('cancelEdit').hidden=true}$('cancelEdit').onclick=resetForm;
$('projectForm').onsubmit=async e=>{e.preventDefault();const original=$('originalName').value,p={name:$('name').value,root:$('root').value,read:$('read').checked,write:$('write').checked,shell:$('shell').checked};try{await json(original?`/projects/${encodeURIComponent(original)}`:'/projects',{method:original?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});resetForm();message('Project saved');await loadProjects()}catch(e){message(e.message,true)}};
async function removeProject(encoded){const name=decodeURIComponent(encoded);if(!confirm(`Remove project "${name}"?`))return;try{await json(`/projects/${encodeURIComponent(name)}`,{method:'DELETE'});message('Project removed');await loadProjects()}catch(e){message(e.message,true)}}
loadApprovals();loadPolicies();loadAudit();loadSecrets();loadProjects();setInterval(loadApprovals,2500);
</script></body></html>
""";
}
